// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: pkg/pb/l4slb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SlbServiceClient is the client API for SlbService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SlbServiceClient interface {
	ChangeMac(ctx context.Context, in *Mac, opts ...grpc.CallOption) (*Bool, error)
	GetMac(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Mac, error)
	AddVip(ctx context.Context, in *VipMeta, opts ...grpc.CallOption) (*Bool, error)
	DelVip(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Bool, error)
	GetAllVips(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Vips, error)
	ModifyVip(ctx context.Context, in *VipMeta, opts ...grpc.CallOption) (*Bool, error)
	ModifyReal(ctx context.Context, in *RealMeta, opts ...grpc.CallOption) (*Bool, error)
	GetVipFlags(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Flags, error)
	GetRealFlags(ctx context.Context, in *Real, opts ...grpc.CallOption) (*Flags, error)
	AddRealForVip(ctx context.Context, in *RealForVip, opts ...grpc.CallOption) (*Bool, error)
	DelRealForVip(ctx context.Context, in *RealForVip, opts ...grpc.CallOption) (*Bool, error)
	ModifyRealsForVip(ctx context.Context, in *ModifiedRealsForVip, opts ...grpc.CallOption) (*Bool, error)
	GetRealsForVip(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Reals, error)
	ModifyQuicRealsMapping(ctx context.Context, in *ModifiedQuicReals, opts ...grpc.CallOption) (*Bool, error)
	GetQuicRealsMapping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QuicReals, error)
	GetStatsForVip(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Stats, error)
	GetLruStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error)
	GetLruMissStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error)
	GetLruFallbackStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error)
	GetIcmpTooBigStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error)
	AddHealthcheckerDst(ctx context.Context, in *Healthcheck, opts ...grpc.CallOption) (*Bool, error)
	DelHealthcheckerDst(ctx context.Context, in *Somark, opts ...grpc.CallOption) (*Bool, error)
	GetHealthcheckersDst(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HcMap, error)
}

type slbServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSlbServiceClient(cc grpc.ClientConnInterface) SlbServiceClient {
	return &slbServiceClient{cc}
}

func (c *slbServiceClient) ChangeMac(ctx context.Context, in *Mac, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/SlbService/changeMac", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) GetMac(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Mac, error) {
	out := new(Mac)
	err := c.cc.Invoke(ctx, "/SlbService/getMac", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) AddVip(ctx context.Context, in *VipMeta, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/SlbService/addVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) DelVip(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/SlbService/delVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) GetAllVips(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Vips, error) {
	out := new(Vips)
	err := c.cc.Invoke(ctx, "/SlbService/getAllVips", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) ModifyVip(ctx context.Context, in *VipMeta, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/SlbService/modifyVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) ModifyReal(ctx context.Context, in *RealMeta, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/SlbService/modifyReal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) GetVipFlags(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Flags, error) {
	out := new(Flags)
	err := c.cc.Invoke(ctx, "/SlbService/getVipFlags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) GetRealFlags(ctx context.Context, in *Real, opts ...grpc.CallOption) (*Flags, error) {
	out := new(Flags)
	err := c.cc.Invoke(ctx, "/SlbService/getRealFlags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) AddRealForVip(ctx context.Context, in *RealForVip, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/SlbService/addRealForVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) DelRealForVip(ctx context.Context, in *RealForVip, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/SlbService/delRealForVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) ModifyRealsForVip(ctx context.Context, in *ModifiedRealsForVip, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/SlbService/modifyRealsForVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) GetRealsForVip(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Reals, error) {
	out := new(Reals)
	err := c.cc.Invoke(ctx, "/SlbService/getRealsForVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) ModifyQuicRealsMapping(ctx context.Context, in *ModifiedQuicReals, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/SlbService/modifyQuicRealsMapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) GetQuicRealsMapping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QuicReals, error) {
	out := new(QuicReals)
	err := c.cc.Invoke(ctx, "/SlbService/getQuicRealsMapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) GetStatsForVip(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/SlbService/getStatsForVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) GetLruStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/SlbService/getLruStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) GetLruMissStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/SlbService/getLruMissStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) GetLruFallbackStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/SlbService/getLruFallbackStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) GetIcmpTooBigStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/SlbService/getIcmpTooBigStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) AddHealthcheckerDst(ctx context.Context, in *Healthcheck, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/SlbService/addHealthcheckerDst", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) DelHealthcheckerDst(ctx context.Context, in *Somark, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/SlbService/delHealthcheckerDst", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slbServiceClient) GetHealthcheckersDst(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HcMap, error) {
	out := new(HcMap)
	err := c.cc.Invoke(ctx, "/SlbService/getHealthcheckersDst", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlbServiceServer is the server API for SlbService service.
// All implementations must embed UnimplementedSlbServiceServer
// for forward compatibility
type SlbServiceServer interface {
	ChangeMac(context.Context, *Mac) (*Bool, error)
	GetMac(context.Context, *Empty) (*Mac, error)
	AddVip(context.Context, *VipMeta) (*Bool, error)
	DelVip(context.Context, *Vip) (*Bool, error)
	GetAllVips(context.Context, *Empty) (*Vips, error)
	ModifyVip(context.Context, *VipMeta) (*Bool, error)
	ModifyReal(context.Context, *RealMeta) (*Bool, error)
	GetVipFlags(context.Context, *Vip) (*Flags, error)
	GetRealFlags(context.Context, *Real) (*Flags, error)
	AddRealForVip(context.Context, *RealForVip) (*Bool, error)
	DelRealForVip(context.Context, *RealForVip) (*Bool, error)
	ModifyRealsForVip(context.Context, *ModifiedRealsForVip) (*Bool, error)
	GetRealsForVip(context.Context, *Vip) (*Reals, error)
	ModifyQuicRealsMapping(context.Context, *ModifiedQuicReals) (*Bool, error)
	GetQuicRealsMapping(context.Context, *Empty) (*QuicReals, error)
	GetStatsForVip(context.Context, *Vip) (*Stats, error)
	GetLruStats(context.Context, *Empty) (*Stats, error)
	GetLruMissStats(context.Context, *Empty) (*Stats, error)
	GetLruFallbackStats(context.Context, *Empty) (*Stats, error)
	GetIcmpTooBigStats(context.Context, *Empty) (*Stats, error)
	AddHealthcheckerDst(context.Context, *Healthcheck) (*Bool, error)
	DelHealthcheckerDst(context.Context, *Somark) (*Bool, error)
	GetHealthcheckersDst(context.Context, *Empty) (*HcMap, error)
	mustEmbedUnimplementedSlbServiceServer()
}

// UnimplementedSlbServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSlbServiceServer struct {
}

func (UnimplementedSlbServiceServer) ChangeMac(context.Context, *Mac) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeMac not implemented")
}
func (UnimplementedSlbServiceServer) GetMac(context.Context, *Empty) (*Mac, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMac not implemented")
}
func (UnimplementedSlbServiceServer) AddVip(context.Context, *VipMeta) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVip not implemented")
}
func (UnimplementedSlbServiceServer) DelVip(context.Context, *Vip) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelVip not implemented")
}
func (UnimplementedSlbServiceServer) GetAllVips(context.Context, *Empty) (*Vips, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllVips not implemented")
}
func (UnimplementedSlbServiceServer) ModifyVip(context.Context, *VipMeta) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyVip not implemented")
}
func (UnimplementedSlbServiceServer) ModifyReal(context.Context, *RealMeta) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyReal not implemented")
}
func (UnimplementedSlbServiceServer) GetVipFlags(context.Context, *Vip) (*Flags, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVipFlags not implemented")
}
func (UnimplementedSlbServiceServer) GetRealFlags(context.Context, *Real) (*Flags, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRealFlags not implemented")
}
func (UnimplementedSlbServiceServer) AddRealForVip(context.Context, *RealForVip) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRealForVip not implemented")
}
func (UnimplementedSlbServiceServer) DelRealForVip(context.Context, *RealForVip) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelRealForVip not implemented")
}
func (UnimplementedSlbServiceServer) ModifyRealsForVip(context.Context, *ModifiedRealsForVip) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyRealsForVip not implemented")
}
func (UnimplementedSlbServiceServer) GetRealsForVip(context.Context, *Vip) (*Reals, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRealsForVip not implemented")
}
func (UnimplementedSlbServiceServer) ModifyQuicRealsMapping(context.Context, *ModifiedQuicReals) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyQuicRealsMapping not implemented")
}
func (UnimplementedSlbServiceServer) GetQuicRealsMapping(context.Context, *Empty) (*QuicReals, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuicRealsMapping not implemented")
}
func (UnimplementedSlbServiceServer) GetStatsForVip(context.Context, *Vip) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatsForVip not implemented")
}
func (UnimplementedSlbServiceServer) GetLruStats(context.Context, *Empty) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLruStats not implemented")
}
func (UnimplementedSlbServiceServer) GetLruMissStats(context.Context, *Empty) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLruMissStats not implemented")
}
func (UnimplementedSlbServiceServer) GetLruFallbackStats(context.Context, *Empty) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLruFallbackStats not implemented")
}
func (UnimplementedSlbServiceServer) GetIcmpTooBigStats(context.Context, *Empty) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIcmpTooBigStats not implemented")
}
func (UnimplementedSlbServiceServer) AddHealthcheckerDst(context.Context, *Healthcheck) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHealthcheckerDst not implemented")
}
func (UnimplementedSlbServiceServer) DelHealthcheckerDst(context.Context, *Somark) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelHealthcheckerDst not implemented")
}
func (UnimplementedSlbServiceServer) GetHealthcheckersDst(context.Context, *Empty) (*HcMap, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealthcheckersDst not implemented")
}
func (UnimplementedSlbServiceServer) mustEmbedUnimplementedSlbServiceServer() {}

// UnsafeSlbServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlbServiceServer will
// result in compilation errors.
type UnsafeSlbServiceServer interface {
	mustEmbedUnimplementedSlbServiceServer()
}

func RegisterSlbServiceServer(s grpc.ServiceRegistrar, srv SlbServiceServer) {
	s.RegisterService(&SlbService_ServiceDesc, srv)
}

func _SlbService_ChangeMac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mac)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).ChangeMac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/changeMac",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).ChangeMac(ctx, req.(*Mac))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_GetMac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).GetMac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/getMac",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).GetMac(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_AddVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VipMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).AddVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/addVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).AddVip(ctx, req.(*VipMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_DelVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).DelVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/delVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).DelVip(ctx, req.(*Vip))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_GetAllVips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).GetAllVips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/getAllVips",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).GetAllVips(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_ModifyVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VipMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).ModifyVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/modifyVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).ModifyVip(ctx, req.(*VipMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_ModifyReal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).ModifyReal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/modifyReal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).ModifyReal(ctx, req.(*RealMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_GetVipFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).GetVipFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/getVipFlags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).GetVipFlags(ctx, req.(*Vip))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_GetRealFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Real)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).GetRealFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/getRealFlags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).GetRealFlags(ctx, req.(*Real))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_AddRealForVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealForVip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).AddRealForVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/addRealForVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).AddRealForVip(ctx, req.(*RealForVip))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_DelRealForVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealForVip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).DelRealForVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/delRealForVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).DelRealForVip(ctx, req.(*RealForVip))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_ModifyRealsForVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifiedRealsForVip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).ModifyRealsForVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/modifyRealsForVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).ModifyRealsForVip(ctx, req.(*ModifiedRealsForVip))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_GetRealsForVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).GetRealsForVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/getRealsForVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).GetRealsForVip(ctx, req.(*Vip))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_ModifyQuicRealsMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifiedQuicReals)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).ModifyQuicRealsMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/modifyQuicRealsMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).ModifyQuicRealsMapping(ctx, req.(*ModifiedQuicReals))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_GetQuicRealsMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).GetQuicRealsMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/getQuicRealsMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).GetQuicRealsMapping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_GetStatsForVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).GetStatsForVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/getStatsForVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).GetStatsForVip(ctx, req.(*Vip))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_GetLruStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).GetLruStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/getLruStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).GetLruStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_GetLruMissStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).GetLruMissStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/getLruMissStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).GetLruMissStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_GetLruFallbackStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).GetLruFallbackStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/getLruFallbackStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).GetLruFallbackStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_GetIcmpTooBigStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).GetIcmpTooBigStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/getIcmpTooBigStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).GetIcmpTooBigStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_AddHealthcheckerDst_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Healthcheck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).AddHealthcheckerDst(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/addHealthcheckerDst",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).AddHealthcheckerDst(ctx, req.(*Healthcheck))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_DelHealthcheckerDst_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Somark)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).DelHealthcheckerDst(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/delHealthcheckerDst",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).DelHealthcheckerDst(ctx, req.(*Somark))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlbService_GetHealthcheckersDst_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlbServiceServer).GetHealthcheckersDst(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SlbService/getHealthcheckersDst",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlbServiceServer).GetHealthcheckersDst(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SlbService_ServiceDesc is the grpc.ServiceDesc for SlbService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SlbService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SlbService",
	HandlerType: (*SlbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "changeMac",
			Handler:    _SlbService_ChangeMac_Handler,
		},
		{
			MethodName: "getMac",
			Handler:    _SlbService_GetMac_Handler,
		},
		{
			MethodName: "addVip",
			Handler:    _SlbService_AddVip_Handler,
		},
		{
			MethodName: "delVip",
			Handler:    _SlbService_DelVip_Handler,
		},
		{
			MethodName: "getAllVips",
			Handler:    _SlbService_GetAllVips_Handler,
		},
		{
			MethodName: "modifyVip",
			Handler:    _SlbService_ModifyVip_Handler,
		},
		{
			MethodName: "modifyReal",
			Handler:    _SlbService_ModifyReal_Handler,
		},
		{
			MethodName: "getVipFlags",
			Handler:    _SlbService_GetVipFlags_Handler,
		},
		{
			MethodName: "getRealFlags",
			Handler:    _SlbService_GetRealFlags_Handler,
		},
		{
			MethodName: "addRealForVip",
			Handler:    _SlbService_AddRealForVip_Handler,
		},
		{
			MethodName: "delRealForVip",
			Handler:    _SlbService_DelRealForVip_Handler,
		},
		{
			MethodName: "modifyRealsForVip",
			Handler:    _SlbService_ModifyRealsForVip_Handler,
		},
		{
			MethodName: "getRealsForVip",
			Handler:    _SlbService_GetRealsForVip_Handler,
		},
		{
			MethodName: "modifyQuicRealsMapping",
			Handler:    _SlbService_ModifyQuicRealsMapping_Handler,
		},
		{
			MethodName: "getQuicRealsMapping",
			Handler:    _SlbService_GetQuicRealsMapping_Handler,
		},
		{
			MethodName: "getStatsForVip",
			Handler:    _SlbService_GetStatsForVip_Handler,
		},
		{
			MethodName: "getLruStats",
			Handler:    _SlbService_GetLruStats_Handler,
		},
		{
			MethodName: "getLruMissStats",
			Handler:    _SlbService_GetLruMissStats_Handler,
		},
		{
			MethodName: "getLruFallbackStats",
			Handler:    _SlbService_GetLruFallbackStats_Handler,
		},
		{
			MethodName: "getIcmpTooBigStats",
			Handler:    _SlbService_GetIcmpTooBigStats_Handler,
		},
		{
			MethodName: "addHealthcheckerDst",
			Handler:    _SlbService_AddHealthcheckerDst_Handler,
		},
		{
			MethodName: "delHealthcheckerDst",
			Handler:    _SlbService_DelHealthcheckerDst_Handler,
		},
		{
			MethodName: "getHealthcheckersDst",
			Handler:    _SlbService_GetHealthcheckersDst_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/l4slb.proto",
}
